#!/bin/bash
set -x
pandoc=~/.cabal/bin/pandoc
$pandoc -s -S -o README.md -t markdown_github advanced_bsv.txt
$pandoc -S -o advanced_bsv.pdf advanced_bsv.txt
$pandoc -s -S -o temp.html -t html5 --toc-depth=2 -c normalize.css -c main.css -c 'http://fonts.googleapis.com/css?family=Droid+Sans:400,700|Droid+Serif' -B before.html -A after.html advanced_bsv.txt
python bsv_syntax.py temp.html > advanced_bsv.html
rm temp.html
